// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDmSldSfYYp0StYgD0jUJ9A1-Nkf8WRpI',
    appId: '1:489525318411:web:072f839e8484cb1a8c080e',
    messagingSenderId: '489525318411',
    projectId: 'mfademoflutter',
    authDomain: 'mfademoflutter.firebaseapp.com',
    storageBucket: 'mfademoflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNF9YsTOm3LPVtn65vyruH90cWDtgSDw',
    appId: '1:489525318411:android:130a3068e5cf781f8c080e',
    messagingSenderId: '489525318411',
    projectId: 'mfademoflutter',
    storageBucket: 'mfademoflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATLb1y5UexBQgwL-ENRQg3yiCyLIVXlPM',
    appId: '1:489525318411:ios:bb1b212965f2a8718c080e',
    messagingSenderId: '489525318411',
    projectId: 'mfademoflutter',
    storageBucket: 'mfademoflutter.firebasestorage.app',
    iosBundleId: 'com.example.mfaMiniDemoBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATLb1y5UexBQgwL-ENRQg3yiCyLIVXlPM',
    appId: '1:489525318411:ios:bb1b212965f2a8718c080e',
    messagingSenderId: '489525318411',
    projectId: 'mfademoflutter',
    storageBucket: 'mfademoflutter.firebasestorage.app',
    iosBundleId: 'com.example.mfaMiniDemoBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDmSldSfYYp0StYgD0jUJ9A1-Nkf8WRpI',
    appId: '1:489525318411:web:072f839e8484cb1a8c080e',
    messagingSenderId: '489525318411',
    projectId: 'mfademoflutter',
    authDomain: 'mfademoflutter.firebaseapp.com',
    storageBucket: 'mfademoflutter.firebasestorage.app',
  );
}
